# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-mttKbHVj7gQpR2Oc5kf2z85NTvnUNPC
"""

def picas_y_fijas_dos_jugadores():
    print("Jugador 1: Ingrese el numero secreto (4 digitos sin ceros y sin repetir)")
    secreto = []

    while len(secreto) < 4:
        n = int(input("digito: "))

        if n < 1 or n > 9:
            print("el numero debe estar entre 1 y 9")
            continue

        if n in secreto:
            print("El dígito ya está en el número secreto. Ingrese otro.")
            continue

        secreto.append(n)

    print("Ahora el usuario 2 intenta adivinar el numero secreto")

    while True:
        intento = []
        print("Ingrese los 4 digitos")

        while len(intento) < 4:
            n = int(input("digito: "))

            if n < 1 or n > 9:
                print("El número debe estar entre 1 y 9")
                continue

            if n in intento:
                print("El dígito ya está en tu intento. Ingrese otro.")
                continue

            intento.append(n)

        picas = 0
        fijas = 0

        for i in range(4):
            if intento[i] == secreto[i]:
                fijas += 1
            elif intento[i] in secreto:
                picas += 1

        print("intento:", intento)
        print("picas:", picas)
        print("fijas:", fijas)

        if fijas == 4:
            print("Felicidades, adivinó el número secreto")
            break


picas_y_fijas_dos_jugadores()